controllers/CustomerAddressController.php
<?php

namespace app\controllers;

use Yii;
use app\models\CustomerAddress;
use app\models\search\CustomerAddressSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CustomerAddressController implements the CRUD actions for CustomerAddress model.
 */
class CustomerAddressController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all CustomerAddress models.
     * @return mixed
     */
    public function actionIndex($customer_id)
    {
        $searchModel = new CustomerAddressSearch();
        $searchModel->customer_id = $customer_id;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single CustomerAddress model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new CustomerAddress model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($customer_id)
    {
        $model = new CustomerAddress();
        $model->customer_id = $customer_id;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash("success", Yii::t('app', "Адрес добавлен"));
            return $this->redirect(['index', 'customer_id' => $customer_id]);
        }

        return $this->renderPartial('_form', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing CustomerAddress model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate()
    {
        if (!Yii::$app->request->isAjax) return false;


        $data = Yii::$app->request->post();
        $model = $this->findModel($data['id']);
        $model->{$data['name']} = $data['val'];


        if ($model->save()){
            return true;
        }else{
            return false;
        }



//        $model = $this->findModel($id);


//        return $this->redirect(['view', 'id' => $model->id]);

    }

    /**
     * Deletes an existing CustomerAddress model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the CustomerAddress model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return CustomerAddress the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = CustomerAddress::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/CustomerController.php
<?php

namespace app\controllers;

use app\components\MyHelper;
use app\models\CompareCreate;
use app\models\UpdateCustomer;
use Yii;
use app\models\Customer;
use app\models\search\CustomerSearch;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\widgets\ActiveForm;

/**
 * CustomerController implements the CRUD actions for Customer model.
 */
class CustomerController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Customer models.
     * @return mixed
     */
    public function actionIndex()
    {

        $searchModel = new CustomerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,

        ]);
    }
    public function actionIndexAjax()
    {
        if (!Yii::$app->request->isAjax)
        {

            $get = Yii::$app->request->queryParams;

            return $this->redirect(['index']);
        }
        $searchModel = new CustomerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->renderAjax('index-ajax', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,

        ]);
    }

    /**
     * Displays a single Customer model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Customer model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */



    public function actionCreate()
    {
        $model = new Customer();

        if (Yii::$app->request->post()) {

            $post = Yii::$app->request->post();

            $data = new CompareCreate();
            $data->first_name = $post['Customer']['first_name'];
            $data->last_name = $post['Customer']['last_name'];
            $data->email_user = $post['Customer']['email_user'];
            $data->phone = $post['Customer']['phone'];
            $data->gender_id = $post['Customer']['gender_id'];
            $data->country_id = $post['Customer']['country_id'];
            $data->city_id = $post['Customer']['city_id'];
            $data->birth_date = $post['Customer']['birth_date'];

            $result = $data->insertCustomer();

            $id = Url::to(['customer/update', 'id' => $result[1]]);
            if ($result[0] == 'create'){
                Yii::$app->session->setFlash("success", Yii::t('app', "Новый клиент добавлен"));
            }else{
                Yii::$app->session->setFlash("success", Yii::t('app', "Такой клиент уже существует, данные обновлены"));
            }

            return $id;
        }

        return $this->renderPartial('_form', [
            'model' => $model,
        ]);
    }


    /**
     * Updates an existing Customer model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {

            $data = new CompareCreate();
            $data->first_name = $model->first_name;
            $data->last_name = $model->last_name;
            $data->gender_id = $model->gender_id;
            $data->metaphone_first_name = metaphone(MyHelper::translit($model->first_name));
            $data->metaphone_last_name = metaphone(MyHelper::translit($model->last_name));

            $compare = $data->compareCustomer();

            if ($compare != $model->id){
                $updateC = new UpdateCustomer();
                $updateC->idNewUser = $compare;
                $updateC->idOldUser = $model->id;
                $updateC->start();

                Yii::$app->session->setFlash("warning", Yii::t('app', "Все данные успешно перенесены"));
                return $this->redirect(['update', 'id' => $compare]);
            }else{
                Yii::$app->session->setFlash("success", Yii::t('app', "Данные обновлены"));
                return $this->redirect(['update', 'id' => $compare]);
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionCompare()
    {
        if (!Yii::$app->request->isAjax) return false;

        $data = Yii::$app->request->post();

        $compare = new CompareCreate();
        $compare->first_name = $data['first_name'];
        $compare->last_name = $data['last_name'];
        $compare->gender_id = $data['gender_id'];
        $compare->metaphone_first_name = metaphone(MyHelper::translit($data['first_name']));
        $compare->metaphone_last_name = metaphone(MyHelper::translit($data['last_name']));
        $res = $compare->compareCustomer();
        return json_encode($res);
    }

    public function actionCits()
    {

        if (!Yii::$app->request->isAjax) return true;
        $post = Yii::$app->request->post();
        $model = new Customer();
        $data = $model->getCityV($post['id']);
        return json_encode($this->renderAjax('_city', [
            'data' => $data,
        ]));
    }

    public function actionSearch()
    {

        if (!Yii::$app->request->isAjax) return true;
        $post = Yii::$app->request->post();
        $result = [];
        switch ($post['wey']){
            case "name":
                $r = Customer::find()
                    ->where([ 'like', 'first_name', $post['value']])
                    ->orWhere(['like', 'metaphone_first_name', metaphone(MyHelper::translit($post['value']))])
                    ->asArray()->all();
                if (!empty($r)) {
                    foreach ($r as $key => $value){
                        $result[$key] = [
                            'label' => "{$value['first_name']} ({$value['last_name']})",
                            'value' => $value['first_name'],
                        ];
                    }
                }
                break;

            case "last":
                $r = Customer::find()
                    ->where([ 'like', 'last_name', $post['value']])
                    ->orWhere(['like', 'metaphone_last_name', metaphone(MyHelper::translit($post['value']))])
                    ->asArray()
                    ->all();
                if (!empty($r)) {
                    foreach ($r as $key => $value){
                        $result[$key] = [
                            'label' => "{$value['last_name']} ({$value['first_name']})",
                            'value' => $value['last_name'],
                        ];
                    }
                }
                break;

            default:
                $result = [];
                break;
        }

        return json_encode($result);
    }






    /**
     * Deletes an existing Customer model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        Yii::$app->session->setFlash("success", Yii::t('app', "Удалено"));
        return $this->redirect(['index']);
    }

    /**
     * Finds the Customer model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Customer the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Customer::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/OrderController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Order;
use app\models\search\OrderSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * OrderController implements the CRUD actions for Order model.
 */
class OrderController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Order models.
     * @return mixed
     */
    public function actionIndex($customer_id)
    {
        $searchModel = new OrderSearch();
        $searchModel->customer_id = $customer_id;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Order model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Order model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($customer_id)
    {
        $model = new Order();
        $model->customer_id = $customer_id;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash("Заказ добавлен", Yii::t('app', "Сохранено"));
            return $this->redirect(['index', 'customer_id' => $customer_id]);
        }

        return $this->render('create', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing Order model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash("success", Yii::t('app', "Сохранено"));
            return $this->redirect(['index', 'customer_id' => $model->customer_id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }


    public function actionGetItem()
    {
        if (!Yii::$app->request->isAjax) return false;

        $data = Yii::$app->request->post();




    }


    /**
     * Deletes an existing Order model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);

        $customer_id = $model->customer_id;

        $model->delete();
        Yii::$app->session->setFlash("success", Yii::t('app', "Удалено"));
        return $this->redirect(['index', 'customer_id' => $customer_id]);
    }

    /**
     * Finds the Order model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Order the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Order::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/customer/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;


/* @var $this yii\web\View */
/* @var $model app\models\search\CustomerSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="customer-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>
    <div class="col-sm-12">
        <div class="row">
            <div class="col-sm-3">
                <?= $form->field($model, 'first_name') ?>
            </div>
            <div class="col-sm-3">
                <?= $form->field($model, 'last_name') ?>
            </div>
            <div class="col-sm-3">
                <?php echo $form->field($model, 'phone') ?>
            </div>
            <div class="col-sm-3">
                <?php echo $form->field($model, 'email_user') ?>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <?= $form->field($model, 'gender_id')->dropDownList($model->getGenders(),['prompt' => '']) ?>
            </div>
            <div class="col-sm-3">
                <?= $form->field($model, 'country_id')->dropDownList($model->getCountryAll(), ['prompt' => '']) ?>
            </div>
            <div class="col-sm-3">
                <?php echo $form->field($model, 'city_id')->dropDownList($model->getCityAll(), ['prompt' => '']) ?>
            </div>
            <div class="col-sm-3">
                <?= $form->field($model, 'birth_date')->widget(\kartik\daterange\DateRangePicker::classname(), [
                    'pluginOptions'=>[
                        'locale' => ['format' => 'Y-MM-DD'],
                        'singleDatePicker'=>true,
                        'showDropdowns'=>true,
                    ],
                    'options' => ['placeholder' => 'Выбрать даты...']
                ]);
                ?>
            </div>
        </div>
        <div class="form-group">
            <?= Html::submitButton('Поиск', ['class' => 'btn btn-primary']) ?>
            <?= Html::a('Сброс', ['customer/index'], ['class' => 'btn btn-default']) ?>
        </div>
    </div>


    <?php ActiveForm::end(); ?>

</div>

views/customer/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use yii\bootstrap\Modal;
use yii\helpers\Url;

use \app\components\MyHelper;

use yii\widgets\ActiveForm;
use yii\widgets\MaskedInput;

use kartik\daterange\DateRangePicker;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\CustomerSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Клиенты';
$this->params['breadcrumbs'][] = $this->title;
?>
    <style>
        ul.ui-autocomplete {
            z-index: 1100;
        }
    </style>
    <div class="customer-index">

        <h1><?= Html::encode($this->title) ?></h1>


<!--        --><?php //Pjax::begin(); ?>
        <?php echo $this->render('_search', ['model' => $searchModel]); ?>
        <p>
            <?= Html::a('Добавить клиента', ['create'], ['class' => 'btn btn-success', 'data-toggle' => "modal", "data-target" => "#modal"]) ?>
        </p>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                ['attribute' => 'gender_id', 'value' => function ($data) {
                    return $data->getGender();
                }, 'filter' => false, 'headerOptions' => ['width' => 100]],


                ['attribute' => 'first_name', 'value' => function ($data) {
                    return Html::a($data->first_name, ['customer/update', 'id' => $data->id]);
                }, 'filter' => false, 'format' => 'raw', 'headerOptions' => ['width' => 130]],

                ['attribute' => 'last_name', 'value' => function ($data) {
                    return Html::a($data->last_name, ['customer/update', 'id' => $data->id]);
                },'filter' => false, 'format' => 'raw', 'headerOptions' => ['width' => 130]],


                ['attribute' => 'country_id', 'value' => function ($data) {

                    return $data->customerAddressOne->country['title'];
                }, 'filter' => false, 'headerOptions' => ['width' => 130]],


                ['attribute' => 'city_id', 'value' => function ($data) {
                    return $data->customerAddressOne->city['title'];
                }, 'filter' => false, 'headerOptions' => ['width' => 130]],


                ['attribute' => 'birth_date', 'value' => function ($data) {
                    return $data['birth_date'];
                }, 'filter' => false, 'format' => ['date', 'dd.MM.Y'], 'headerOptions' => ['width' => 100]],


                ['attribute' => 'phone', 'value' => function ($data) {
                    return MyHelper::phoneFormatter($data->customerAddressOne['phone']);
                }, 'filter' => false, 'headerOptions' => ['width' => 250]],

                ['attribute' => 'email_user', 'value' => function ($data) {
                    return $data->customerAddressOne['email_user'];
                }, 'filter' => false, 'headerOptions' => ['width' => 100]],

                ['attribute' => 'qty_orders','value' => function($data){
                    return count($data->orders);
                },'filter' => false,'headerOptions' => ['width' => 30]],

                ['attribute' => 'total_income', 'value' => function($data){
                    $res = $data->getOrdersSum();
                    return $res ? $res : 0;
                }, 'filter' => false,'headerOptions' => ['width' => 50]],

                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{prewOrder} {addOrder} {update} {delete}',
                    'buttons' => [

                        'prewOrder' => function ($url, $model, $key) {
                            return Html::a('', ['order/index', 'customer_id' => $model->id, 'page' => Yii::$app->request->get('page')],
                                [
                                    'class' => 'glyphicon glyphicon-shopping-cart',
                                    'title' => \Yii::t('yii', 'Просотр заказов')
                                ]);
                        },
                        'addOrder' => function ($url, $model) {
                            return Html::a('', ['order/create', 'customer_id' => $model->id],
                                [
                                    'class' => 'glyphicon glyphicon-plus',
                                    'title' => \Yii::t('yii', 'Добавить заказ')
                                ]);
                        }
                    ]
                ],
            ],
        ]); ?>

<!--        --><?php //Pjax::end(); ?>


        <?php
        Modal::begin([
            'header' => 'Добавить клиента',
            'id' => 'modal',
            'size' => 'modal-lg',
        ]);
        ?>
        <div id='modal-content'
        <div class="customer-form">

            <?= Yii::$app->runAction('customer/create', ['option_id' => $model->id]) ?>

        </div>
    </div>
<?php Modal::end(); ?>

    </div>
<?php

$create = Url::to(['customer/create']);
$cits = Url::to(['customer/cits']);
$search = Url::to(['customer/search']);


$js = <<<JS
    $("body").keydown("input", function(e) {
        if(e.keyCode === 13) {
          e.preventDefault();
        }
    });
    
    $("body").on("input", "#customer-first_name,#customersearch-first_name,#customer-last_name,#customersearch-last_name",function(e){
        
        if(e.keyCode === 13) {
           e.preventDefault();
        }
        
        let idInput = "#" + $(this).attr('id') + "";
        
        let wey = '';
        if (idInput == "#customer-first_name" || idInput == "#customersearch-first_name"){
            wey = "name";
        }else {
            wey = "last";
        }
        
        
        let value = $(e.target).val();
        let data = {value:value, wey:wey};
        
        data[yii.getCsrfParam()] = yii.getCsrfToken();

        if (value.length >= 2){
            $.ajax({
            url: "{$search}",
            data: data,
            type: 'POST',
            context: $(this),
            success: function (data) {
                if (!data) {
                    console.log('not data');
                }
                let views = JSON.parse(data);
                $("#itemsSearch").html(views);
                $(idInput).autocomplete({
                  source: views
                });  
            },
            error: function () {
                console.log('Что то пошло не так');
            }
            });
           
        }
    });
    
     

    $("body").on('change', "#customer-country_id", function() {
        var id = $(this).val();
        var data = {id:id};
        data[yii.getCsrfParam()] = yii.getCsrfToken();
        $.ajax({
            url: "{$cits}",
            data: data,
            type: 'POST',
            context: $(this),
            success: function (data) {
                if (!data) {
                    console.log('not data');
                }
                let views = JSON.parse(data);
                $("#cits").html(views);
                
            },
            error: function () {
                console.log('Что то пошло не так');
            }
        });
    });

    $("body").on('click', "#customer-form-s", function(e) {
        var data = {};
        $('#customer-form').find ('input, textearea, select').each(function() {
          data[this.name] = $(this).val();
        });
        
        if (data["Customer[first_name]"].length != 0 || data["Customer[last_name]"].length != 0){
            e.preventDefault();
            data[yii.getCsrfParam()] = yii.getCsrfToken();
            
            
            $.ajax({
            url: "{$create}",
            data: data,
            type: 'POST',
            context: $(this),
            success: function (data) {
                if (!data) {
                    console.log('not data');
                }
                // let views = JSON.parse(data);
                // $('#modal').modal('hide');
                // $("form#customer-form").trigger('reset');
                
                window.location.href=data
                // console.log(data);
                // $(".content").html(data);
                
            },
            error: function () {
                console.log('Что то пошло не так');
            }
        });
            
            
           
            
        }

    });

JS;
$this->registerJs($js, yii\web\View::POS_END);
?>

views/customer/update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $model app\models\Customer */

$this->title = 'Клиент: ' . $model->first_name . ' ' . $model->last_name;
$this->params['breadcrumbs'][] = ['label' => 'Клиенты', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
    <style>
        #alert {
            display: none;
        }
    </style>
    <div class="alert alert-warning" id="alert" role="alert"></div>
<div class="customer-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <h3>Сумарный доход: <b><?=$model->getOrdersSum()?></b></h3>
    <div class="btn-group btn-group-justified">
        <div class="btn-group">
            <?=Html::a('Основные данные', ['customer/update', 'id' => $model->id], ['class' => 'btn btn-default'])?>
        </div>
        <div class="btn-group">
            <?=Html::a('Заказы', ['order/index', 'customer_id' => $model->id], ['class' => 'btn btn-default'])?>
        </div>
        <div class="btn-group">
            <?=Html::a('Адреса клиента', ['customer-address/index', 'customer_id' => $model->id], ['class' => 'btn btn-default'])?>
        </div>
    </div>

    <br>
    <hr>

    <?php $form = ActiveForm::begin(); ?>

    <div class="row">
        <div class="tab-content">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="row">

                    <div class="col-sm-3">
                        <?= $form->field($model, 'first_name')->textInput(['autocomplete' => 'off', 'maxlength' => true]) ?>
                    </div>
                    <div class="col-sm-3">
                        <?= $form->field($model, 'last_name')->textInput(['autocomplete' => 'off', 'maxlength' => true]) ?>
                    </div>
                    <div class="col-sm-3">
                        <?= $form->field($model, 'gender_id')->dropDownList($model->getGenders()) ?>
                    </div>
                    <div class="col-sm-3">
                        <?= $form->field($model, 'birth_date')->widget(\kartik\daterange\DateRangePicker::classname(), [
                            'pluginOptions'=>[
                                'locale' => ['format' => 'Y-MM-DD'],
                                'singleDatePicker'=>true,
                                'showDropdowns'=>true,
                            ],
                            'options' => ['placeholder' => 'Выбрать даты...']
                        ]);
                        ?>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success', 'id' => 'customer-form-s']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>
<?php

$url = Url::to(['customer/compare']);
$customer = Url::to(['customer/update', 'id' => '']);
$js = <<<JS
    $("body").keydown("input", function(e) {
        if(e.keyCode === 13) {
          e.preventDefault();
        }
    });

    $("body").on('change', ".form-control", function() {
        var id = '"{$model->id}"';
        var first_name = $("#customer-first_name").val();
        var last_name = $("#customer-last_name").val();
        var gender_id = $("#customer-gender_id").val();
        var urlCustomer = "{$customer}";
        
        
        var data = {first_name:first_name, last_name:last_name, gender_id:gender_id};
        data[yii.getCsrfParam()] = yii.getCsrfToken();
        $.ajax({
            url: "{$url}",
            data: data,
            type: 'POST',
            context: $(this),
            success: function (data) {
                if (!data) {
                    console.log('not data');
                }
                let views = JSON.parse(data);
                
                if (data != 'false' && data != id){
                    
                    let text = 'Внимание клиент с такими данными существует, в случае сохранения все данные текущего клиента, перенесутся к существующему. ';
                    text += '<p><b><a href=' + urlCustomer + views + ' target="_blank">Посмотреть существующего клиента</a></b></p>';
                    $("#alert").css('display', 'block');
                    $("#alert").html(text);
                }else {
                    $("#alert").css('display', 'none');
                }
                
                
            },
            error: function () {
                console.log('Что то пошло не так');
            }
        });
        
        console.log(data);
        
    });
    
    



JS;
$this->registerJs($js, yii\web\View::POS_END);

?>