controllers/CustomerAddressController.php
<?php

namespace app\controllers;

use Yii;
use app\models\CustomerAddress;
use app\models\search\CustomerAddressSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * CustomerAddressController implements the CRUD actions for CustomerAddress model.
 */
class CustomerAddressController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all CustomerAddress models.
     * @return mixed
     */
    public function actionIndex($customer_id)
    {
        $searchModel = new CustomerAddressSearch();
        $searchModel->customer_id = $customer_id;
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }


    /**
     * Displays a single CustomerAddress model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new CustomerAddress model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate($customer_id)
    {
        $model = new CustomerAddress();
        $model->customer_id = $customer_id;
        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            Yii::$app->session->setFlash("success", Yii::t('app', "Адрес добавлен"));
            return $this->redirect(['index', 'customer_id' => $customer_id]);
        }

        return $this->renderPartial('_form', [
            'model' => $model,
        ]);
    }

    /**
     * Updates an existing CustomerAddress model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate()
    {
        if (!Yii::$app->request->isAjax) return false;


        $data = Yii::$app->request->post();
        $model = $this->findModel($data['id']);
        $model->{$data['name']} = $data['val'];


        if ($model->save()){
            return true;
        }else{
            return false;
        }



//        $model = $this->findModel($id);


//        return $this->redirect(['view', 'id' => $model->id]);

    }

    /**
     * Deletes an existing CustomerAddress model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the CustomerAddress model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return CustomerAddress the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = CustomerAddress::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

controllers/CustomerController.php
<?php

namespace app\controllers;

use app\components\MyHelper;
use app\models\CompareCreate;
use app\models\UpdateCustomer;
use Yii;
use app\models\Customer;
use app\models\search\CustomerSearch;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\widgets\ActiveForm;

/**
 * CustomerController implements the CRUD actions for Customer model.
 */
class CustomerController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all Customer models.
     * @return mixed
     */
    public function actionIndex()
    {

        $searchModel = new CustomerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,

        ]);
    }
    public function actionIndexAjax()
    {
        if (!Yii::$app->request->isAjax)
        {

            $get = Yii::$app->request->queryParams;

            return $this->redirect(['index']);
        }
        $searchModel = new CustomerSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->renderAjax('index-ajax', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,

        ]);
    }

    /**
     * Displays a single Customer model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Customer model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */



    public function actionCreate()
    {
        $model = new Customer();

        if (Yii::$app->request->post()) {

            $post = Yii::$app->request->post();

            $data = new CompareCreate();
            $data->first_name = $post['Customer']['first_name'];
            $data->last_name = $post['Customer']['last_name'];
            $data->email_user = $post['Customer']['email_user'];
            $data->phone = $post['Customer']['phone'];
            $data->gender_id = $post['Customer']['gender_id'];
            $data->country_id = $post['Customer']['country_id'];
            $data->city_id = $post['Customer']['city_id'];
            $data->birth_date = $post['Customer']['birth_date'];

            $result = $data->insertCustomer();

            $id = Url::to(['customer/update', 'id' => $result[1]]);
            if ($result[0] == 'create'){
                Yii::$app->session->setFlash("success", Yii::t('app', "Новый клиент добавлен"));
            }else{
                Yii::$app->session->setFlash("success", Yii::t('app', "Такой клиент уже существует, данные обновлены"));
            }

            return $id;
        }

        return $this->renderPartial('_form', [
            'model' => $model,
        ]);
    }


    /**
     * Updates an existing Customer model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post())) {

            $data = new CompareCreate();
            $data->first_name = $model->first_name;
            $data->last_name = $model->last_name;
            $data->gender_id = $model->gender_id;
            $data->metaphone_first_name = metaphone(MyHelper::translit($model->first_name));
            $data->metaphone_last_name = metaphone(MyHelper::translit($model->last_name));

            $compare = $data->compareCustomer();

            if ($compare != $model->id){
                $updateC = new UpdateCustomer();
                $updateC->idNewUser = $compare;
                $updateC->idOldUser = $model->id;
                $updateC->start();

                Yii::$app->session->setFlash("warning", Yii::t('app', "Все данные успешно перенесены"));
                return $this->redirect(['update', 'id' => $compare]);
            }else{
                Yii::$app->session->setFlash("success", Yii::t('app', "Данные обновлены"));
                return $this->redirect(['update', 'id' => $compare]);
            }

            return $this->redirect(['view', 'id' => $model->id]);
        }

        return $this->render('update', [
            'model' => $model,
        ]);
    }

    public function actionCompare()
    {
        if (!Yii::$app->request->isAjax) return false;

        $data = Yii::$app->request->post();

        $compare = new CompareCreate();
        $compare->first_name = $data['first_name'];
        $compare->last_name = $data['last_name'];
        $compare->gender_id = $data['gender_id'];
        $compare->metaphone_first_name = metaphone(MyHelper::translit($data['first_name']));
        $compare->metaphone_last_name = metaphone(MyHelper::translit($data['last_name']));
        $res = $compare->compareCustomer();
        return json_encode($res);
    }

    public function actionCits()
    {

        if (!Yii::$app->request->isAjax) return true;
        $post = Yii::$app->request->post();
        $model = new Customer();
        $data = $model->getCityV($post['id']);
        return json_encode($this->renderAjax('_city', [
            'data' => $data,
        ]));
    }

    public function actionSearch()
    {

        if (!Yii::$app->request->isAjax) return true;
        $post = Yii::$app->request->post();
        $result = [];
        switch ($post['wey']){
            case "name":
                $r = Customer::find()
                    ->where([ 'like', 'first_name', $post['value']])
                    ->orWhere(['like', 'metaphone_first_name', metaphone(MyHelper::translit($post['value']))])
                    ->asArray()->all();
                if (!empty($r)) {
                    foreach ($r as $key => $value){
                        $result[$key] = [
                            'label' => "{$value['first_name']} ({$value['last_name']})",
                            'value' => $value['first_name'],
                        ];
                    }
                }
                break;

            case "last":
                $r = Customer::find()
                    ->where([ 'like', 'last_name', $post['value']])
                    ->orWhere(['like', 'metaphone_last_name', metaphone(MyHelper::translit($post['value']))])
                    ->asArray()
                    ->all();
                if (!empty($r)) {
                    foreach ($r as $key => $value){
                        $result[$key] = [
                            'label' => "{$value['last_name']} ({$value['first_name']})",
                            'value' => $value['last_name'],
                        ];
                    }
                }
                break;

            default:
                $result = [];
                break;
        }

        return json_encode($result);
    }






    /**
     * Deletes an existing Customer model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();
        Yii::$app->session->setFlash("success", Yii::t('app', "Удалено"));
        return $this->redirect(['index']);
    }

    /**
     * Finds the Customer model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Customer the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Customer::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }
}

views/customer-address/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\widgets\MaskedInput;

$countries = $model->customer->getCountryAll();

/* @var $this yii\web\View */
/* @var $model app\models\CustomerAddress */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="customer-address-form">

    <?php $form = ActiveForm::begin([
        'action' => \yii\helpers\Url::to(['customer-address/create', 'customer_id' => $model->customer_id]),
    ]); ?>

    <div class="row">
        <div class="tab-content">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="row">

                    <div class="col-sm-6">
                        <?= $form->field($model, 'email_user')->widget(MaskedInput::className(), ['mask' => '*{3,20}@*{3,10}.*{2,5}'])->textInput(['placeholder' => $model->getAttributeLabel('email_user')]); ?>
                    </div>
                    <div class="col-sm-6">
                        <?= $form->field($model, 'phone')->widget(MaskedInput::className(), ['mask' => '+99(999)999 99 99'])->textInput(['placeholder' => $model->getAttributeLabel('phone')]) ?>
                    </div>
                </div>
                <div class="row">
                   <div class="col-sm-3">
                        <?= $form->field($model, 'country_id')->dropDownList($countries) ?>
                    </div>
                    <div class="col-sm-3" id="cits">
                        <?= $form->field($model, 'city_id')->dropDownList($model->customer->getCityV((array_key_first($countries)))) ?>
                    </div>
                    <div class="col-sm-3">
                        <?= $form->field($model, 'default')->dropDownList(['Нет', 'Да']) ?>
                    </div>
                    <div class="col-sm-3" id="cits">
                        <?= $form->field($model, 'sort')->textInput(['type' => 'number']) ?>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="form-group">
        <?= Html::submitButton('Сохранить', ['class' => 'btn btn-success']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/customer-address/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\search\CustomerAddressSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="customer-address-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
        'options' => [
            'data-pjax' => 1
        ],
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'customer_id') ?>

    <?= $form->field($model, 'country_id') ?>

    <?= $form->field($model, 'city_id') ?>

    <?= $form->field($model, 'phone') ?>

    <?php // echo $form->field($model, 'email_user') ?>

    <?php // echo $form->field($model, 'default') ?>

    <?php // echo $form->field($model, 'sort') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

views/customer-address/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\CustomerAddress */

$this->title = 'Create Customer Address';
$this->params['breadcrumbs'][] = ['label' => 'Customer Addresses', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="customer-address-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/customer-address/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\widgets\Pjax;
use app\components\MyHelper;
use yii\widgets\MaskedInput;

use yii\bootstrap\Modal;
use yii\helpers\Url;

/* @var $this yii\web\View */
/* @var $searchModel app\models\search\CustomerAddressSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$customer = $searchModel->customer;

$this->title = "Адреса клиента: {$customer->first_name} {$customer->last_name}";
$this->params['breadcrumbs'][] = ['label' => 'Клиенты', 'url' => ['customer/index']];
$this->params['breadcrumbs'][] = ['label' => 'Клиент: ' . " {$customer->first_name} {$customer->last_name}", 'url' => ['customer/update', 'id' => $searchModel->customer_id]];
$this->params['breadcrumbs'][] = $this->title;
?>
    <div class="customer-address-index">

        <h1><?= Html::encode($this->title) ?></h1>

        <p>
            <?= Html::a('Добавить адрес', ['create'], ['class' => 'btn btn-success', 'data-toggle' => "modal", "data-target" => "#modal"]) ?>
        </p>

        <?php Pjax::begin(); ?>
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'columns' => [
                ['class' => 'yii\grid\SerialColumn', 'headerOptions' => ['width' => '50']],


                ['attribute' => 'phone', 'value' => function ($data) {
                    return MaskedInput::widget([
                        'name' => 'phone',
                        'mask' => '+99(999)999 99 99',
                        'value' => $data->phone,
                        'options' => ['class' => 'form-control update']
                    ]);
                },
                    'headerOptions' => ['width' => 200],
                    'format' => 'raw'
                ],

                ['attribute' => 'country_id', 'value' => function ($data) {
                    return Html::dropDownList('country_id', $data->country_id, $data->customer->getCountryAll(), [
                        'class' => 'form-control update country',
                        'address_id' => $data->id
                    ]);
                },
                    'filter' => $searchModel->customer->getCountryAll(),
                    'headerOptions' => ['width' => 130],
                    'format' => 'raw',
                ],

                ['attribute' => 'city_id', 'value' => function ($data) {
                    return Html::dropDownList('city_id', $data->city_id, $data->customer->getCityV($data->country_id), [
                        'class' => "form-control update city_row_{$data->id}",
                    ]);
                },
                    'filter' => $searchModel->customer->getCountryAll(),
                    'headerOptions' => ['width' => 130],
                    'format' => 'raw'
                ],


                ['attribute' => 'email_user', 'value' => function ($data) {

                    return MaskedInput::widget([
                        'name' => 'email_user',
                        'mask' => '*{3,20}@*{3,10}.*{2,5}',
                        'value' => $data->email_user,
                        'options' => ['class' => 'form-control update']
                    ]);
                },
                    'headerOptions' => ['width' => 200],
                    'format' => 'raw'
                ],

                ['attribute' => 'default', 'value' => function ($data) {
                    return Html::dropDownList('default', $data->default, ['Нет', 'Да'], ['class' => 'form-control update default']);
                },
                    'filter' => ['Нет', 'Да'],
                    'headerOptions' => ['width' => 130],
                    'format' => 'raw'
                ],

                ['attribute' => 'sort', 'value' => function ($data) {
                    return Html::input('number', 'sort', $data->sort, ['class' => 'form-control update']);
                },
                    'headerOptions' => ['width' => 200],
                    'format' => 'raw'
                ],


                ['class' => 'yii\grid\ActionColumn',
                    'template' => "{delete}",
                    'headerOptions' => ['width' => '50'],
                ]
            ],
        ]); ?>

        <?php Pjax::end(); ?>

    </div>


<?php
Modal::begin([
    'header' => 'Добавить адрес',
    'id' => 'modal',
    'size' => 'modal-lg',
]);
?>
    <div id='modal-content'
    <div class="customer-form">

        <?= Yii::$app->runAction('customer-address/create', ['customer_id' => $searchModel->customer_id]) ?>

    </div>
    </div>
<?php Modal::end(); ?>


<?php
$urlUpdate = Url::to(['customer-address/update']);
$cits = Url::to(['customer/cits']);

$js = <<<JS
    $("body").keydown("input", function(e) {
        if(e.keyCode === 13) {
          e.preventDefault();
        }
    });

    
    $("body").on('change', ".country,#customeraddress-country_id", function() {
        var id = $(this).val();
        console.log($(this).attr('id'));
        var data = {id:id};
        data[yii.getCsrfParam()] = yii.getCsrfToken();
        var orderId = $(this).parent().parent().attr('data-key');
        $.ajax({
            url: "{$cits}",
            data: data,
            type: 'POST',
            context: $(this),
            success: function (data) {
                if (!data) {
                    console.log('not data');
                }
                let views = JSON.parse(data);
                
                if ($(this).attr('id') == 'customeraddress-country_id'){
                    $("#customeraddress-city_id").html(views);
                }else {
                    $(".city_row_" + orderId).html(views);
                }
                
                
            },
            error: function () {
                console.log('Что то пошло не так');
            }
        });
        
    });
    

    $("body").on('change', ".update", function() {
        var id = $(this).parent().parent().attr('data-key');
        var val = $(this).val();
        var val_name = $(this).attr('name');
        var data = {id:id, val:val, name:val_name};
        data[yii.getCsrfParam()] = yii.getCsrfToken();
        $.ajax({
            url: "{$urlUpdate}",
            data: data,
            type: 'POST',
            context: $(this),
            success: function (data) {
                if (!data) {
                    console.log('not data');
                }
                if (data == true && val_name == 'default' && val == 1){
                    $('select[name=default]').val(0);
                    $(this).val(val)
                }
                console.log(data);
                // alert("Сохранено");
                
            },
            error: function () {
                console.log('Что то пошло не так');
            }
        });
        
        console.log(data);
        
    });
    
    



JS;
$this->registerJs($js, yii\web\View::POS_END);

?>

views/customer-address/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model app\models\CustomerAddress */

$this->title = 'Update Customer Address: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Customer Addresses', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Update';
?>
<div class="customer-address-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

views/customer-address/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model app\models\CustomerAddress */

$this->title = $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Customer Addresses', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
\yii\web\YiiAsset::register($this);
?>
<div class="customer-address-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            'id',
            'customer_id',
            'country_id',
            'city_id',
            'phone',
            'email_user:email',
            'default',
            'sort',
            'created_at',
            'updated_at',
        ],
    ]) ?>

</div>